services:
  web:
    image: nginx:alpine
    container_name: kishori_portfolio
    volumes:
      - ./html:/usr/share/nginx/html:ro
    restart: always
    networks:
      private_network:
        ipv4_address: 172.16.0.18

networks:
  private_network:
    external: true