services:
  app:
    image: nginx:alpine
    container_name: app
    networks:
      private_network:
        ipv4_address: 172.16.0.18
    # ports:
    #   - "8080:80"

networks:
  private_network:
    external: true